import Script from "next/script";
import "../styles/globals.css";

export const metadata = {
	title: "WazzApp Web",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				{children}

				<Script src="../js/microphonePlugin.js" />
			</body>
		</html>
	);
}

